name: Run Passing Tests

on:
  push:
    branches:
      - main  # or the branch you want to run tests on
  pull_request:
    branches:
      - main  # optional: run on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Specify the version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          pytest --maxfail=0 --exitfirst
